version: "3.0"

services:

  database:
    image: postgres_4pe
#    user: pe_reports
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: pe_reports_postgres
#    user: 1000:1000
    restart: always
    env_file:
      - ./config/dev_database.env
    networks:
      - database_network
    volumes:
        - ../database_pe_staging/pg_data:/dev_database/
        - ../pe_reports/src/pe_reports/data/pg_restore.sh:/docker-entrypoint-initdb.d/pg_restore.sh
        - ../pe_reports/src/pe_reports/data/backups/pedb_dump.sql:/pedb_dump.sql
    ports:
      - "5437:5432"
    container_name: staging_pe_peports

networks:
  database_network:
    #name: theDjangoNetwork
    driver: bridge
